### ISSUE TITLE
IETFify (but not NMDAify) YANG model

### ISSUE THREAD

**Issue by plajjan** [sartura/sip-plugin#2]
We should probably move towards NMDA but more on that later, for now there are a few simple fixes we can do.

Container "sip-config" should be called just "sip". "sip-status" should be "sip-state".

There is a "enabled" leaf just under "sip". Partly I wonder if it's really necessary to have this, but if we do, shouldn't it default to "true" ? I think there's a problem with having a leaf in a model just below a non-presence container, so if you actually want to have it as it is now then the container needs to be a presence container.

**Comment by mislavn** [comment]
I'll make a new branch with the proposed changes.

The leaf "enabled" is there to start/stop asterisk, do you think it's better if the plugin track's state of the asterisk program (restart after crash) or move that logic to the NETCONF client via operational data and RPC call's?

**Comment by mislavn** [comment]
I made some changes to YANG model: https://github.com/sartura/sip-plugin/blob/yang/yang/sip%402017-08-09.yang
